import sys

import flatbuffers

# Generated by `flatc`.
import MyGame.Sample.Color
import MyGame.Sample.Equipment
import MyGame.Sample.Monster
import MyGame.Sample.Vec3
import MyGame.Sample.Weapon

# Construct a Builder with 1024 byte backing array.
builder = flatbuffers.Builder(1024)
weapon_one = builder.CreateString('Sword')
weapon_two = builder.CreateString('Axe')

# Create the first `Weapon` ('Sword').
MyGame.Sample.Weapon.Start(builder)
MyGame.Sample.Weapon.AddName(builder, weapon_one)
MyGame.Sample.Weapon.AddDamage(builder, 3)
sword = MyGame.Sample.Weapon.End(builder)

# Create the second `Weapon` ('Axe').
MyGame.Sample.Weapon.Start(builder)
MyGame.Sample.Weapon.AddName(builder, weapon_two)
MyGame.Sample.Weapon.AddDamage(builder, 5)
axe = MyGame.Sample.Weapon.End(builder)

# Use the generated helper to create the weapons vector from offsets.
# weapons = MyGame.Sample.Monster.CreateWeaponsVector(builder, [sword, axe])
MyGame.Sample.Monster.StartWeaponsVector(builder, 2)
builder.PrependUOffsetTRelative(axe)
builder.PrependUOffsetTRelative(sword)
weapons = builder.EndVector()

# Create a `vector` representing the inventory of the Orc. Each number
# could correspond to an item that can be claimed after he is slain.
# inv = MyGame.Sample.Monster.CreateInventoryVector(builder, range(0, 10))
MyGame.Sample.Monster.StartInventoryVector(builder, 10)
for i in reversed(range(0, 10)):
    builder.PrependByte(i)
inv = builder.EndVector()


path_points = [
    MyGame.Sample.Vec3.Vec3T(x=1.0, y=2.0, z=3.0),
    MyGame.Sample.Vec3.Vec3T(x=4.0, y=5.0, z=6.0),
]
# path = MyGame.Sample.Monster.CreatePathVector(builder, path_points)
MyGame.Sample.Monster.StartPathVector(builder, len(path_points))
for p in reversed(path_points):
    vec = MyGame.Sample.Vec3.CreateVec3(builder, p.x, p.y, p.z)
    builder.PrependUOffsetTRelative(vec)
path = builder.EndVector()

# Serialize a name for our monster, called "Orc".
name = builder.CreateString("Orc")

# Create our monster by using `Monster.Start()` and `Monster.End()`.
MyGame.Sample.Monster.Start(builder)
MyGame.Sample.Monster.AddPos(builder,
    MyGame.Sample.Vec3.CreateVec3(builder, 1.0, 2.0, 3.0))
MyGame.Sample.Monster.AddHp(builder, 300)
MyGame.Sample.Monster.AddName(builder, name)
MyGame.Sample.Monster.AddInventory(builder, inv)
MyGame.Sample.Monster.AddColor(builder,
                                        MyGame.Sample.Color.Color().Red)
MyGame.Sample.Monster.AddWeapons(builder, weapons)
MyGame.Sample.Monster.AddEquippedType(
    builder, MyGame.Sample.Equipment.Equipment().Weapon)
MyGame.Sample.Monster.AddEquipped(builder, axe)
MyGame.Sample.Monster.AddPath(builder, path)
orc = MyGame.Sample.Monster.End(builder)

# Call `Finish()` to instruct the builder that this monster is complete.
builder.Finish(orc)

# This must be called after `Finish()`.
buf = builder.Output() # Of type `bytearray`.

# Get an accessor to the root object inside the buffer.
monster = MyGame.Sample.Monster.Monster.GetRootAs(buf, 0)

# Note: We use `0` for the offset here, which is typical for most buffers
# you would read.  If you wanted to read from the `builder.Bytes` directly,
# you would need to pass in the offset of `builder.Head()`, as the builder
# constructs the buffer backwards, so may not start at offset 0.

hp = monster.Hp()
mana = monster.Mana()
name = monster.Name()

pos = monster.Pos()
x = pos.X()
y = pos.Y()
z = pos.Z()

print(f"Monster '{name}' has {hp} HP and {mana} Mana at position ({x}, {y}, {z})")
